### ISSUE TITLE
download link is not working 

### ISSUE THREAD

**Issue by hassanayoub1985** [SubGlitch1/DentalXrayAI#1]
Hello,
The dataset pretrained model link is not working.
Another thing, which format to download from dataset?
Thanks

**Comment by SubGlitch1** [comment]
> Hello,
> 
> The dataset pretrained model link is not working.
> 
> Another thing, which format to download from dataset?
> 
> Thanks

Hey. My website is down for the moment for maintenance. The pre trained model is in this GitHub repo named best.pt. Just clone this repository and then run the object detection Python file and the website will be available on your localhost. Let me know if you have any other questions.

**Comment by NoahOksuz** [comment]
> Hello,
> 
> The dataset pretrained model link is not working.
> 
> Another thing, which format to download from dataset?
> 
> Thanks

Hey. My website is down for maintenance at the moment. I will upload the pretrained model to this repository in a few hours when I have time. The model is in pt format.

**Comment by hassanayoub1985** [comment]
Hello thank you, waiting

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hassanayoub1985** [comment]
Hi, Any update?

**Comment by NoahOksuz** [comment]
hey man sorry i completely forgot about this. i have added the model to the github repo you can try it out.
