### ISSUE TITLE
face issue in dataset link 

### ISSUE THREAD

**Issue by regression1607** [SubGlitch1/DentalXrayAI#2]
please help to resolve this issue 
all the cmd run succesfully but still the best.pt fill not found 
![Screenshot 2024-03-02 121754](https://github.com/SubGlitch1/DentalXrayAI/assets/115173416/05a8b9b3-82b3-46a4-b5fc-861977f368f7)
![Screenshot 2024-03-02 121800](https://github.com/SubGlitch1/DentalXrayAI/assets/115173416/ad2cad7c-7b03-4f7f-801b-268c1ee52d47)

please contact me at mail ekanshrajput1607@gmail.com

**Comment by NoahOksuz** [comment]
@regression1607 i have added the best.pt model. update your repo and try again :100:
